version: '3.8'

services:
  mongodb_order:
    image: mongo:latest
    container_name: mongodb_order_service
    ports:
      - "27018:27017" # Use a different port to avoid conflict
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-order-data:/data/db
    command: mongod --bind_ip_all

  app:
    build: .
    container_name: order-service
    ports:
      - "8081:8080" # Use a different port to avoid conflict
    environment:
      MONGO_URI: mongodb://root:example@mongodb_order_service:27017
      DATABASE_NAME: orders
      SERVER_ADDRESS: :8080
    depends_on:
      - mongodb_order

volumes:
  mongo-order-data:

networks:
  backend: